import { SUPPORT_CONTACT } from '@/lib/content/contact';

import { StatusFooter, StatusHeader } from './StatusChrome';
import { StatusMessage } from './StatusMessage';
import { SupportPanel } from './SupportPanel';

/**
 * The in-app "Something went wrong" page (design: Something Went Wrong;
 * design/SHOPPING-STATE.md §56), rendered by `app/error.tsx` and
 * `app/global-error.tsx`.
 *
 * Copy is the design's, verbatim. Reduced chrome by decision: when the system
 * may be unhealthy, offer TRY AGAIN and the homepage, not ordering or account
 * actions.
 *
 * The host-level twin of this page is `public/500.html`, generated by
 * `lib/status-pages/render.ts` — keep the two in step.
 */
export function ServerErrorPage({ onRetry }: { onRetry: () => void }) {
  return (
    <>
      <StatusHeader contactJump={SUPPORT_CONTACT !== null} />
      <main>
        <StatusMessage
          kind="error"
          mark="error"
          eyebrow="Error 500"
          title="Something didn’t go to plan."
          lede="We’re having trouble loading this page right now. Please try again in a moment."
          primary={{ label: 'Try again', onClick: onRetry }}
          secondary={{ label: 'Back to homepage', href: '/' }}
        >
          <SupportPanel contact={SUPPORT_CONTACT} />
        </StatusMessage>
      </main>
      <StatusFooter />
    </>
  );
}
